### ISSUE TITLE
Compare Python and Julia

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#1]
We will either use Python or Julia for our implementation.  Please create a list of pros and cons of each option so that we can settle on a choice.

**Comment by EmilSoleymani** [comment]
#### Videos used for research
- [Julia: Is it better than Python?](https://youtu.be/565EDmwCSZw)
- *Not used much* > [Intro to Game Development using GameZero | GameZero.jl, Julia & VS Code](https://youtu.be/SSYV8gC2UkQ)
- *Not used much* > [What is LLVM?](https://youtu.be/JhCsnws7vuw)

## Overview of Julia
Julia is a **HLL** that was developed specifically for data science / machine learning. The key purpose of Julia is to provide users with fast speeds like the low-level languages C/C++, while having simple high-level language syntax. Graphics programming seems to be possible (for GUI), however Python seems to have better support for this (*pygame* and *tkinter* are much better graphics libraries). Julia achieves its speed through *JIT* (just-in-time) compilation at runtime using `LLVM` framework. 
> *"Julia is a high-level, dynamic programming language, designed to give users the speed of C/C++ while remaining as easy to use as Python"* - from [article](https://www.freecodecamp.org/news/learn-julia-programming-language/)

## Advantages of Julia over Python
- **SPEED** : Julia has C-like speeds while remaining as simple as Python!
- Easy to use math functions
- No need for external libraries to handle linear algebra (no need for numpy!)
- Built in parallelization, shared memory threads, etc. Good for utilizing machine resources (e.g. multiple cores)
- Julia allows for both OOP and *functional* programming, while Python only allows for OOP
- Julia is dynamically typed with the option to specify types before hand (I feel like specified types make code more understandable) [Note: I think python has an external library that allows for specifying types too]
- **Can use Julia to call functions from C, FORTRAN, Python, etc..** [What if we just call the original FORTRAN subroutines in a simple Julia program as a simple first version of software? Or even develop most parts in python since it is familiar, calling it through Julia, and leaving big calculations for native Julia code to take advantage of speed?] [See link for more info](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code)

## Advantages of Python over Julia
- We don't have to learn a new language? [this could also be a disadvantage, I like learning new things. Furthermore, we can call python subroutines from Julia so this could be mitigated]
- *Much larger community*. Python has existed much longer, there's an infinite stream of tutorials, blogs, books, etc underlining and detailing everything you can do with it
- More 3rd party libraries: larger community + longer lifespan = more 3rd party libraries
- *Pygame*: a very useful 3rd party library for graphics programming

## Final Remarks
Given all the facts listed above, I think Julia is an exciting, effective, yet simple language that would be worth exploring for this project. The major point that makes me consider this is that fact that we can port Python, C or FORTRAN subroutines which eliminates the biggest issue of using Julia - namely, learning advanced Julia techniques. With learning just the basics of Julia, we can take advantage of its high performance capabilities while using some Python code we can develop via our established Python skills (or as mentioned, even reuse the given FORTRAN code).

**Comment by smiths** [comment]
Great information @EmilSoleymani.  There are definitely some positive aspects to Julia!  I would feel better about Julia if we were confident that we can build a nice GUI.  Can you find an example of a Julia project online that has a nice GUI?

I think we can start with using Julia when you start coding.  At the beginning we'll keep asking ourselves how well it is working, so that we can switch to Python if necessary.

**Comment by EmilSoleymani** [comment]
[This article](https://towardsdatascience.com/6-julia-frameworks-to-create-desktop-guis-and-web-apps-9ae1a941f115) lists some very good external Julia libraries for building GUIs, with `GTK.jl` being the most notable one. This library seems to have some great [documentation](https://juliagraphics.github.io/Gtk.jl/latest/manual/gettingStarted/).
I found [this video tutorial](https://youtu.be/BDteSX9Eat0) in which a GUI application is made in Julia. Although his videos aren't the most professional he seems to have the most content on Youtube concerning Julia - especially graphics development. In the linked video there are many graphics applications shown, e.g a calculator app.

**Comment by smiths** [comment]
Great links @EmilSoleymani.  This builds my confidence that Julia is a viable option.  Let's proceed with that plan.  (We can always change our minds later.)
