### ISSUE TITLE
Remove `dir.dat` from version control

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#120]
I'm assuming that the `dir.dat` file is used to remember the input file folder.  This is a good idea.  Having this file under version control creates problems though because each developer will have to either reset their file to commit, or they'll update it, causing potential (minor) problems for other developers.

Is there any reason we can't just remove this file from version control?

**Comment by EmilSoleymani** [comment]
Removed from version control in eaaf3f5f0ae72bb22b67ee8d892bb65f90851dfa. Julia now first checks if this file exists. If not it generates the file and leaves in blank.

This was already in the `.gitignore`, not sure why it managed to stay in the version control. Since I wanted to get rid of the other files in its directory anyways, I updated `.gitignore` to list `src/.data/*`.

**Comment by smiths** [comment]
Sounds good!
