### ISSUE TITLE
Explain the purpose of the Project.toml file in our README file.

### ISSUE THREAD

**Issue by EmilSoleymani** [smiths/vdisp#34]
We should explain the purpose of the Project.toml file in our README file.

**Comment by EmilSoleymani** [comment]
Added new section in README

**Comment by smiths** [comment]
@EmilSoleymani, when you close an issue by making an addition, please add the commit hash.  This helps with traceability.  For instance, for this issue the commit is e7d59601165ded9e964540f7bcf587c437f0cb2c.  Since this commit is in a branch, I guess it will disappear when merged with Master.  When an issue is closed by a PR you can provide that information.  (I think I saw that you have already been doing that.)
