### ISSUE TITLE
Learn FORTRAN

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#6]

**Comment by smiths** [comment]
As part of this issue, modify the [FORTRAN code](https://github.com/smiths/vdisp/tree/main/fortran_src) so that the warnings no longer appear.  

I've protected the `main` branch, so you will need to create a new branch to make your changes.  You can then do a pull request so that we can pull the new code into the `main` branch.

**Comment by EmilSoleymani** [comment]
### Learning FORTRAN
After watching [a video tutorial](https://youtu.be/d_ZNWPNzspg) on FORTRAN I felt comfortable with the basics of FORTRAN 77 and some of its differences with the newer, modern Fortran. 

### Warning Fixes
There were 2 types of warnings that repeated multiple times throughout the code. One of these was the outdated way to terminate `DO` loops.  Previously, the developer would label a `DO` loop with a certain number, then simply write this number at the beginning of the last line of the loop, as follows:
```  
      DO 2010 I=2,N
2010  H(I)=X(I)-X(I-1)
```
In modern Fortran, the developer is required to terminate the loop by either writing `ENDDO` after the final line of the body (no label is needed for the loop), or the label followed by `CONTINUE`. Examples of both given below:
```
      DO I=2,N
      H(I)=X(I)-X(I-1)
      ENDDO
```
```
      DO 2010 I=2,N
      H(I)=X(I)-X(I-1)
2010  CONTINUE
```
> Note: I chose the first fix in each of my updates to the code
> Note: In modern Fortran, we no longer capitalize all commands, but I continued to do so to follow the rest of the code

The next type of warning arises from the use of a deprecated feature from old FORTRAN - the `arithmetic if` statement. IN old FORTRAN, `IF (expr) label1, label2, label3` jumps to `label1` if `exrp<0`, jumps to `label2` if `expr==0`, or jumps to `label3` if `expr>0`. Example from legacy source code:
```
      IF(N-L)35,35,30
30    IE(L,1)=IE(L-1,1)
```
Since it branches to the same label if less than or equal to zero, we can `GOTO 30` if `(N-L) > 0`, else do 30:
```
      IF(N-L .gt. 0) GOTO 30
35    ! Code at label 35    
      ! Goto to line after code at label 35 to maintain sequential order
30    IE(L,1)=IE(L-1,1)
```
After lots of fixing, the code compiles with **no warnings**, and works correctly. I saved an old output, `VDOU_OLD.DAT` from before the warning fixes and it matched the new `VDOU.DAT` generated from the version of the code with no warnings.
> All updates pushed to `fortranupdate` branch

**Comment by EmilSoleymani** [comment]
@smiths For future reference, I was wondering if there is a naming convention you prefer for new branches

**Comment by smiths** [comment]
Great work @EmilSoleymani.  Your explanations are clear.  I particularly like that you verified that the output is unchanged.

I don't really have a branch naming convention, other than to use wip for [work in progress](https://stackoverflow.com/questions/15763059/github-what-is-a-wip-branch).  I really haven't found it necessary to adopt a convention for branch naming, but we can adopt a convention should it become useful.

When your branch is done, please submit a pull request.  I'd like to make sure that I've set up the protected `main` branch correctly.  It is also a good way for us to discuss your changes.

**Comment by EmilSoleymani** [comment]
Pull request created. I was blocked from merging as desired.
