### ISSUE TITLE
Documentation for getSurchargePressure function

### ISSUE THREAD

**Issue by EmilSoleymani** [smiths/vdisp#74]
I have found out how to get the textbook version of calculations to correspond to the calculations done in the code. I have successfully recalculated the same test cases as yesterday, this time using the original formula from the textbook. I should soon make a pdf of my handwritten calculations, and also add a dostring for the `getSurchargePressure` function.

**Comment by EmilSoleymani** [comment]
Hand calculations here:
[Test Case Surcharge Pressure.pdf](https://github.com/smiths/vdisp/files/8871489/Test.Case.Surcharge.Pressure.1.pdf)

**Comment by smiths** [comment]
Looks good @EmilSoleymani, although you are still writing with a closer connection to the code than I would like.  If an Engineer was asked to calculate the surcharge pressure at a given depth, they wouldn't be using an array in their calculations.  There is also some information missing, since you give three different values for P[7] (0.1195866, 0, 1.000).
