### ISSUE TITLE
Add arrow to water table and footing depth indicators

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#99]
The water table and footing depth indicators are ambiguous with respect to where they are pointing.  Is it the middle of the tab shape, or one of the edges?  I think the middle makes the most sense, and we could add an arrow within the tab to show the centre of the tab.  The point that the arrow points to would be the depth.

**Comment by EmilSoleymani** [comment]
Instead of allowing users to put the foundation depth / ground water table depth anywhere, the sliders now have a step size of the dx of the layer they are currently in. This forces the handle to end up on a soil layer. The code would have done this rounding regardless, but it is now less ambiguous for the user as they are explicitly shown that the depth gets rounded to this value. User must adjust their input by adding more subdivisions or an extra layer in order to achieve the precision they desire.

This was achieved in commits 6deca43ee37ec10a01be6feb3ccb963d71096010 and 9584ccf19e8e00b60485264fb2a3d53863b160df

**Comment by smiths** [comment]
@EmilSoleymani, I tested the new foundation/water table depth selectors.  Very nice!  However, they don't seem to line up with the tick marks that are shown on the right of the slice of soil.  If they are using the same increments, then shouldn't they line up?
